exclude: 'bower_components/**'

linters:
  NameFormat:
    enabled: false
  ColorVariable:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  BorderZero:
    enabled: false
  Indentation:
    enabled: false
  SpaceAfterVariableName:
    enabled: false
  PropertySpelling:
    enabled: false
  LeadingZero:
    enabled: false
