TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.PrettyEmbedYoutube': TRUE

Jonnitto:
	PrettyEmbedYoutube:
		includeJavascript:
			Live: true
			Backend: true
		imgResultion: 'maxresdefault'
		embed:
			class: 'pretty-embed'
			src: '//www.youtube.com/embed'
		lightbox:
			class: 'popup-youtube'
			link: '//www.youtube.com/watch?v='