TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.PrettyEmbedYoutube': TRUE
    userInterface:
      translation:
        autoInclude:
          'Jonnitto.PrettyEmbedYoutube': ['Main', 'NodeTypes/YouTube']

Jonnitto:
  PrettyEmbedYoutube:
    includeCss: TRUE
    includeJavascript: TRUE
    imgResultion: maxresdefault
    maximumWidth: 1920
    wrapper: FALSE # CSS Class for a wrapper (e.g. 'container')
    embed:
      class: 'embed-youtube'
      video: 'https://www.youtube.com/embed/'
      playlist: 'https://www.youtube.com/embed/videoseries?list='
    lightbox:
      class: 'popup-youtube'
      video: 'https://www.youtube.com/watch?v='
      playlist: 'https://www.youtube.com/playlist?list='
