TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.PrettyEmbedYoutube': TRUE

Jonnitto:
  PrettyEmbedYoutube:
    includeCss: true
    includeJavascript: true
    imgResultion: 'maxresdefault'
    embed:
      class: 'embed-youtube'
      video: 'https://www.youtube.com/embed/'
      playlist: 'https://www.youtube.com/embed/videoseries?list='
    lightbox:
      class: 'popup-youtube'
      video: 'https://www.youtube.com/watch?v='
      playlist: 'https://www.youtube.com/playlist?list='
