TYPO3:
  Neos:
    typoScript:
      autoInclude:
        'Jonnitto.PrettyEmbedYoutube': TRUE

Jonnitto:
  PrettyEmbedYoutube:
    includeCss: true
    includeJavascript: true
    imgResultion: 'maxresdefault'
    embed:
      class: 'embed-youtube'
      src: 'https://www.youtube.com/embed/'
    lightbox:
      class: 'popup-youtube'
      href: 'https://www.youtube.com/watch?v='